#!/bin/sh
set -e

# ── Docker Secrets support ──────────────────────────────────────────
# For each VAR in the list, if VAR_FILE is set, read the file contents
# into VAR. This allows using Docker Swarm secrets or any file-based
# secret injection (e.g. /run/secrets/<name>).
for secret_var in APP_SECRET NEXTAUTH_SECRET DATABASE_URL ORCHESTRATOR_API_KEY LICENSE_KEY; do
  file_var="${secret_var}_FILE"
  eval file_path="\$$file_var"
  if [ -n "$file_path" ]; then
    if [ -f "$file_path" ]; then
      val=$(cat "$file_path" | tr -d '\n')
      export "$secret_var"="$val"
      echo "[entrypoint] Loaded $secret_var from $file_path"
    else
      echo "[entrypoint] WARNING: $file_var=$file_path but file does not exist"
    fi
  fi
done

# ── Database bootstrap ──────────────────────────────────────────────
# Postgres only since the SQLite cutover. DATABASE_URL is mandatory; the
# container refuses to boot rather than silently falling back to a stale
# default.
if [ -z "$DATABASE_URL" ]; then
  echo "[entrypoint] ERROR: DATABASE_URL is not set."
  echo "[entrypoint]   Expected: postgresql://<user>:<pass>@<host>:5432/<db>?schema=public"
  exit 1
fi

# Apply pending Prisma migrations (idempotent — no-op if everything is
# already in sync). The prisma CLI is invoked via its build entry point
# directly because the runner image does not preserve node_modules/.bin
# symlinks across the COPY layers.
echo "[entrypoint] Applying Prisma migrations..."
node node_modules/prisma/build/index.js migrate deploy

# Idempotent seed: default tenant, security policy, RBAC permission
# catalogue and system roles. Pre-bundled to a self-contained seed.js
# during the Docker build, so no tsx / TypeScript runtime needed here.
echo "[entrypoint] Running idempotent seed..."
node prisma/seed.js

# Auto-load orchestrator API key from shared volume (generated by the
# orchestrator the first time it boots).
if [ -z "$ORCHESTRATOR_API_KEY" ] && [ -f /app/orchestrator_data/.api_key ]; then
  export ORCHESTRATOR_API_KEY=$(cat /app/orchestrator_data/.api_key | tr -d '\n')
  echo "[entrypoint] Loaded ORCHESTRATOR_API_KEY from orchestrator shared volume"
fi

# Security checks
if [ -z "$NEXTAUTH_SECRET" ]; then
  echo "[entrypoint] ⚠ WARNING: NEXTAUTH_SECRET is not set. Sessions will use an insecure default key."
  echo "[entrypoint]   Generate one with: openssl rand -base64 32"
fi

echo "[entrypoint] Starting..."
exec "$@"
