#!/bin/sh
set -e

# ── Docker Secrets support ──────────────────────────────────────────
# For each VAR in the list, if VAR_FILE is set, read the file contents
# into VAR. This allows using Docker Swarm secrets or any file-based
# secret injection (e.g. /run/secrets/<name>).
for secret_var in APP_SECRET NEXTAUTH_SECRET DATABASE_URL ORCHESTRATOR_API_KEY LICENSE_KEY; do
  file_var="${secret_var}_FILE"
  eval file_path="\$$file_var"
  if [ -n "$file_path" ]; then
    if [ -f "$file_path" ]; then
      val=$(cat "$file_path" | tr -d '\n')
      export "$secret_var"="$val"
      echo "[entrypoint] Loaded $secret_var from $file_path"
    else
      echo "[entrypoint] WARNING: $file_var=$file_path but file does not exist"
    fi
  fi
done

# ── Database bootstrap ──────────────────────────────────────────────
# The demo image (DEMO_MODE=true, baked at build time) intercepts every
# API call through src/lib/demo/demo-api.ts and returns canned mock data.
# It never touches Prisma, so we skip the migration + seed steps and the
# mandatory DATABASE_URL check.
if [ "$DEMO_MODE" = "true" ]; then
  echo "[entrypoint] DEMO_MODE=true, skipping Prisma migrations and seed"
else
  # Postgres only since the SQLite cutover. DATABASE_URL is mandatory;
  # the container refuses to boot rather than silently falling back to a
  # stale default.
  if [ -z "$DATABASE_URL" ]; then
    echo "[entrypoint] ERROR: DATABASE_URL is not set."
    echo "[entrypoint]   Expected: postgresql://<user>:<pass>@<host>:5432/<db>?schema=public"
    exit 1
  fi

  # Apply pending Prisma migrations (idempotent, no-op if everything is
  # already in sync). The prisma CLI is invoked via its build entry point
  # directly because the runner image does not preserve node_modules/.bin
  # symlinks across the COPY layers.
  echo "[entrypoint] Applying Prisma migrations..."
  node node_modules/prisma/build/index.js migrate deploy

  # Idempotent seed: default tenant, security policy, RBAC permission
  # catalogue and system roles. Pre-bundled to a self-contained seed.js
  # during the Docker build, so no tsx / TypeScript runtime needed here.
  echo "[entrypoint] Running idempotent seed..."
  node prisma/seed.js
fi

# Refuse to boot with the .env.example placeholder. Compose injects the
# same value into both the frontend (ORCHESTRATOR_API_KEY) and the
# orchestrator (PROXCENTER_API_API_KEY), so silently clearing it on the
# frontend would leave the orchestrator still expecting the placeholder
# and auth would break asymmetrically. Fail loudly so the operator fixes
# .env once instead of chasing 401s later.
if [ "$ORCHESTRATOR_API_KEY" = "your-orchestrator-api-key-change-me" ]; then
  echo "[entrypoint] ERROR: ORCHESTRATOR_API_KEY is set to the .env.example placeholder." >&2
  echo "[entrypoint]   Replace it in .env with a real key: openssl rand -hex 32" >&2
  exit 1
fi

# Auto-load orchestrator API key from shared volume (generated by the
# orchestrator the first time it boots).
if [ -z "$ORCHESTRATOR_API_KEY" ] && [ -f /app/orchestrator_data/.api_key ]; then
  export ORCHESTRATOR_API_KEY=$(cat /app/orchestrator_data/.api_key | tr -d '\n')
  echo "[entrypoint] Loaded ORCHESTRATOR_API_KEY from orchestrator shared volume"
fi

# Security checks: refuse missing or placeholder secrets. Both .env.example
# files and the build-time fallback in src/lib/auth/config.ts ship known
# stub values; if any of those reach a container at runtime the operator
# forgot to provision real secrets and sessions would all share the same
# key across every install.
check_secret() {
  var_name=$1
  eval value="\$$var_name"
  case "$value" in
    "" | \
    "your-nextauth-secret-here" | "your-nextauth-secret-change-me" | \
    "your-app-secret-here" | "your-app-secret-change-me" | \
    "build-time-placeholder")
      echo "[entrypoint] ERROR: $var_name is empty or set to a placeholder value." >&2
      echo "[entrypoint]   Replace it in .env with a real secret: openssl rand -base64 32" >&2
      exit 1
      ;;
  esac
}

# The published demo image bakes DEMO_MODE=true and ships without any
# real .env. demo-api intercepts every API call and never reaches Prisma
# or auth middleware, so requiring real secrets here would regress demo
# bootstrap from "warn and run" to "exit and fail" with no benefit.
if [ "$DEMO_MODE" != "true" ]; then
  check_secret NEXTAUTH_SECRET
  check_secret APP_SECRET
fi

echo "[entrypoint] Starting..."
exec "$@"
