// sudoersTemplate builds a /etc/sudoers.d/proxcenter body from the
// orchestrator allowlist. Each command carries its own absolute
// ExecutablePath (served by the backend — see AllowedCommand in
// internal/api/ssh_allowlist.go); prefixes without an executablePath
// are shell-wrapped (e.g. `for br in $(ovs-vsctl list-br)`) and are
// covered by a scoped `/bin/sh` entry, with a matching UI warning.
//
// Keeping all prefix → path knowledge on the Go side is deliberate:
// new allowlist entries only need to be added in one place.

export interface AllowlistCommand {
  prefix: string
  executablePath?: string
  category: string
  description: string
  usedBy: string
}

export interface AllowlistCategoryShape {
  id: string
  label: string
  description: string
  commands: AllowlistCommand[]
}

const SUDO_USER = 'proxcenter'

function escapeSudoersLine(s: string): string {
  return s.replace(/[\r\n]/g, ' ')
}

export function buildSudoersTemplate(categories: AllowlistCategoryShape[]): { body: string, shellWrappedCount: number } {
  const lines: string[] = [
    '# /etc/sudoers.d/proxcenter',
    '# Generated by ProxCenter (/settings?tab=ssh-commands).',
    '# Validate with: visudo -c -f /etc/sudoers.d/proxcenter',
    `Defaults:${SUDO_USER} !requiretty`,
    ''
  ]

  let shellWrappedCount = 0

  for (const cat of categories) {
    const byPath = new Map<string, string[]>()
    for (const cmd of cat.commands) {
      const path = cmd.executablePath
      if (!path) {
        shellWrappedCount++
        continue
      }
      if (!byPath.has(path)) byPath.set(path, [])
      byPath.get(path)!.push(cmd.prefix)
    }

    if (byPath.size === 0) continue

    lines.push(`# ${escapeSudoersLine(cat.label)}`)
    const paths = Array.from(byPath.keys()).sort((a, b) => a.localeCompare(b))
    lines.push(`${SUDO_USER} ALL=(ALL) NOPASSWD: ${paths.join(', ')}`)
    lines.push('')
  }

  if (shellWrappedCount > 0) {
    lines.push('# Shell-wrapped commands (e.g. for-loop over OVS bridges for sFlow config).')
    lines.push('# Remove this line to disable shell-wrapped features such as Network Flows sFlow enable.')
    lines.push(`${SUDO_USER} ALL=(ALL) NOPASSWD: /bin/sh -c *`)
    lines.push('')
  }

  return { body: lines.join('\n'), shellWrappedCount }
}

export function buildInstallCommand(body: string): string {
  return `cat > /etc/sudoers.d/proxcenter <<'EOF'\n${body}\nEOF\nchmod 440 /etc/sudoers.d/proxcenter\nvisudo -c -f /etc/sudoers.d/proxcenter`
}
