// frontend/src/lib/vmware/pagination.ts
/**
 * Helper to follow vSphere SOAP `RetrievePropertiesEx` continuation tokens.
 * vCenter truncates large responses (default ~100 objects) and returns a
 * `<token>` in the `<returnval>` when more pages are available; clients must
 * call `ContinueRetrievePropertiesEx` with that token until the response no
 * longer contains one.
 *
 * The function returns the **concatenation** of every page's raw XML text so
 * callers can keep using their existing regex-based parsers unchanged.
 */
export async function retrieveAllPropertiesEx(
  soapReq: (body: string) => Promise<{ text: string }>,
  initialBody: string,
  propertyCollector: string,
  maxIterations = 100,
): Promise<string> {
  const pages: string[] = []
  let response = await soapReq(initialBody)

  pages.push(response.text)
  let token = extractToken(response.text)
  let iterations = 0

  while (token && iterations < maxIterations) {
    iterations++
    response = await soapReq(buildContinueBody(propertyCollector, token))
    pages.push(response.text)
    token = extractToken(response.text)
  }

  if (token) {
    console.warn(
      `[vmware-pagination] hit max iterations (${maxIterations}); some results may be missing`,
    )
  }

  return pages.join('\n')
}

/**
 * Extract the continuation token from a `RetrievePropertiesEx` /
 * `ContinueRetrievePropertiesEx` response. The token, when present, is a
 * direct child of `<returnval>` and appears **before** any `<objects>` block.
 * Restricting the search to that prefix avoids false positives if a property
 * value happens to contain a literal `<token>` element.
 */
export function extractToken(responseText: string): string | null {
  const returnval = responseText.match(/<returnval[^>]*>([\s\S]*?)<\/returnval>/)?.[1]

  if (!returnval) return null
  const beforeObjects = returnval.split(/<objects[\s>]/)[0]
  const m = beforeObjects.match(/<token>([^<]+)<\/token>/)

  return m?.[1] ?? null
}

function buildContinueBody(propertyCollector: string, token: string): string {
  // Token is generated by vCenter and consists of safe characters
  // (typically base64-ish), but escape just in case.
  const safeToken = token.replace(/&/g, '&amp;').replace(/</g, '&lt;')

  return `<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:vim25">
  <soapenv:Body>
    <urn:ContinueRetrievePropertiesEx>
      <urn:_this type="PropertyCollector">${propertyCollector}</urn:_this>
      <urn:token>${safeToken}</urn:token>
    </urn:ContinueRetrievePropertiesEx>
  </soapenv:Body>
</soapenv:Envelope>`
}
