// Authored from the ISO/IEC 27001:2022 Annex A control set (identifiers + concise titles). ISO normative text is copyright and not reproduced.
import type { FrameworkControl } from './types'

export const ISO_27001_2022_CONTROLS: FrameworkControl[] = [
  // A.5 Organizational controls (37)
  { id: 'A.5.1',  title: 'Policies for information security',               family: 'Organizational' },
  { id: 'A.5.2',  title: 'Information security roles and responsibilities',  family: 'Organizational' },
  { id: 'A.5.3',  title: 'Segregation of duties',                           family: 'Organizational' },
  { id: 'A.5.4',  title: 'Management responsibilities',                      family: 'Organizational' },
  { id: 'A.5.5',  title: 'Contact with authorities',                         family: 'Organizational' },
  { id: 'A.5.6',  title: 'Contact with special interest groups',             family: 'Organizational' },
  { id: 'A.5.7',  title: 'Threat intelligence',                              family: 'Organizational' },
  { id: 'A.5.8',  title: 'Information security in project management',       family: 'Organizational' },
  { id: 'A.5.9',  title: 'Inventory of information and other assets',        family: 'Organizational' },
  { id: 'A.5.10', title: 'Acceptable use of information and other assets',   family: 'Organizational' },
  { id: 'A.5.11', title: 'Return of assets',                                 family: 'Organizational' },
  { id: 'A.5.12', title: 'Classification of information',                    family: 'Organizational' },
  { id: 'A.5.13', title: 'Labelling of information',                         family: 'Organizational' },
  { id: 'A.5.14', title: 'Information transfer',                             family: 'Organizational' },
  { id: 'A.5.15', title: 'Access control',                                   family: 'Organizational' },
  { id: 'A.5.16', title: 'Identity management',                              family: 'Organizational' },
  { id: 'A.5.17', title: 'Authentication information',                       family: 'Organizational' },
  { id: 'A.5.18', title: 'Access rights',                                    family: 'Organizational' },
  { id: 'A.5.19', title: 'Information security in supplier relationships',   family: 'Organizational' },
  { id: 'A.5.20', title: 'Addressing security in supplier agreements',       family: 'Organizational' },
  { id: 'A.5.21', title: 'Managing security in the ICT supply chain',        family: 'Organizational' },
  { id: 'A.5.22', title: 'Monitoring and review of supplier services',       family: 'Organizational' },
  { id: 'A.5.23', title: 'Information security for use of cloud services',   family: 'Organizational' },
  { id: 'A.5.24', title: 'Information security incident management planning', family: 'Organizational' },
  { id: 'A.5.25', title: 'Assessment and decision on information security events', family: 'Organizational' },
  { id: 'A.5.26', title: 'Response to information security incidents',       family: 'Organizational' },
  { id: 'A.5.27', title: 'Learning from information security incidents',     family: 'Organizational' },
  { id: 'A.5.28', title: 'Collection of evidence',                           family: 'Organizational' },
  { id: 'A.5.29', title: 'Information security during disruption',           family: 'Organizational' },
  { id: 'A.5.30', title: 'ICT readiness for business continuity',            family: 'Organizational' },
  { id: 'A.5.31', title: 'Legal, statutory, regulatory and contractual requirements', family: 'Organizational' },
  { id: 'A.5.32', title: 'Intellectual property rights',                     family: 'Organizational' },
  { id: 'A.5.33', title: 'Protection of records',                            family: 'Organizational' },
  { id: 'A.5.34', title: 'Privacy and protection of personal information',   family: 'Organizational' },
  { id: 'A.5.35', title: 'Independent review of information security',       family: 'Organizational' },
  { id: 'A.5.36', title: 'Compliance with policies and standards',           family: 'Organizational' },
  { id: 'A.5.37', title: 'Documented operating procedures',                  family: 'Organizational' },

  // A.6 People controls (8)
  { id: 'A.6.1', title: 'Screening',                                          family: 'People' },
  { id: 'A.6.2', title: 'Terms and conditions of employment',                 family: 'People' },
  { id: 'A.6.3', title: 'Information security awareness, education and training', family: 'People' },
  { id: 'A.6.4', title: 'Disciplinary process',                               family: 'People' },
  { id: 'A.6.5', title: 'Responsibilities after termination or change of employment', family: 'People' },
  { id: 'A.6.6', title: 'Confidentiality or non-disclosure agreements',       family: 'People' },
  { id: 'A.6.7', title: 'Remote working',                                     family: 'People' },
  { id: 'A.6.8', title: 'Information security event reporting',               family: 'People' },

  // A.7 Physical controls (14)
  { id: 'A.7.1',  title: 'Physical security perimeters',                      family: 'Physical' },
  { id: 'A.7.2',  title: 'Physical entry',                                    family: 'Physical' },
  { id: 'A.7.3',  title: 'Securing offices, rooms and facilities',            family: 'Physical' },
  { id: 'A.7.4',  title: 'Physical security monitoring',                      family: 'Physical' },
  { id: 'A.7.5',  title: 'Protecting against physical and environmental threats', family: 'Physical' },
  { id: 'A.7.6',  title: 'Working in secure areas',                           family: 'Physical' },
  { id: 'A.7.7',  title: 'Clear desk and clear screen',                       family: 'Physical' },
  { id: 'A.7.8',  title: 'Equipment siting and protection',                   family: 'Physical' },
  { id: 'A.7.9',  title: 'Security of assets off-premises',                   family: 'Physical' },
  { id: 'A.7.10', title: 'Storage media',                                      family: 'Physical' },
  { id: 'A.7.11', title: 'Supporting utilities',                               family: 'Physical' },
  { id: 'A.7.12', title: 'Cabling security',                                   family: 'Physical' },
  { id: 'A.7.13', title: 'Equipment maintenance',                              family: 'Physical' },
  { id: 'A.7.14', title: 'Secure disposal or re-use of equipment',             family: 'Physical' },

  // A.8 Technological controls (34)
  { id: 'A.8.1',  title: 'User endpoint devices',                             family: 'Technological' },
  { id: 'A.8.2',  title: 'Privileged access rights',                          family: 'Technological' },
  { id: 'A.8.3',  title: 'Information access restriction',                    family: 'Technological' },
  { id: 'A.8.4',  title: 'Access to source code',                             family: 'Technological' },
  { id: 'A.8.5',  title: 'Secure authentication',                             family: 'Technological' },
  { id: 'A.8.6',  title: 'Capacity management',                               family: 'Technological' },
  { id: 'A.8.7',  title: 'Protection against malware',                        family: 'Technological' },
  { id: 'A.8.8',  title: 'Management of technical vulnerabilities',           family: 'Technological' },
  { id: 'A.8.9',  title: 'Configuration management',                          family: 'Technological' },
  { id: 'A.8.10', title: 'Information deletion',                               family: 'Technological' },
  { id: 'A.8.11', title: 'Data masking',                                       family: 'Technological' },
  { id: 'A.8.12', title: 'Data leakage prevention',                           family: 'Technological' },
  { id: 'A.8.13', title: 'Information backup',                                 family: 'Technological' },
  { id: 'A.8.14', title: 'Redundancy of information processing facilities',   family: 'Technological' },
  { id: 'A.8.15', title: 'Logging',                                            family: 'Technological' },
  { id: 'A.8.16', title: 'Monitoring activities',                              family: 'Technological' },
  { id: 'A.8.17', title: 'Clock synchronisation',                              family: 'Technological' },
  { id: 'A.8.18', title: 'Use of privileged utility programs',                family: 'Technological' },
  { id: 'A.8.19', title: 'Installation of software on operational systems',   family: 'Technological' },
  { id: 'A.8.20', title: 'Networks security',                                  family: 'Technological' },
  { id: 'A.8.21', title: 'Security of network services',                      family: 'Technological' },
  { id: 'A.8.22', title: 'Segregation of networks',                           family: 'Technological' },
  { id: 'A.8.23', title: 'Web filtering',                                      family: 'Technological' },
  { id: 'A.8.24', title: 'Use of cryptography',                               family: 'Technological' },
  { id: 'A.8.25', title: 'Secure development life cycle',                     family: 'Technological' },
  { id: 'A.8.26', title: 'Application security requirements',                 family: 'Technological' },
  { id: 'A.8.27', title: 'Secure system architecture and engineering principles', family: 'Technological' },
  { id: 'A.8.28', title: 'Secure coding',                                      family: 'Technological' },
  { id: 'A.8.29', title: 'Security testing in development and acceptance',    family: 'Technological' },
  { id: 'A.8.30', title: 'Outsourced development',                            family: 'Technological' },
  { id: 'A.8.31', title: 'Separation of development, test and production environments', family: 'Technological' },
  { id: 'A.8.32', title: 'Change management',                                  family: 'Technological' },
  { id: 'A.8.33', title: 'Test information',                                   family: 'Technological' },
  { id: 'A.8.34', title: 'Protection of information systems during audit testing', family: 'Technological' },
]
