// GENERATED by scripts/extract-oscal-controls.ts — do not edit by hand.
import type { FrameworkControl } from './types'

export const NIST_800_53_R5_CONTROLS: FrameworkControl[] = [
  {
    "id": "AC-1",
    "title": "Policy and Procedures",
    "family": "Access Control"
  },
  {
    "id": "AC-11",
    "title": "Device Lock",
    "family": "Access Control"
  },
  {
    "id": "AC-11.1",
    "title": "Pattern-hiding Displays",
    "family": "Access Control"
  },
  {
    "id": "AC-12",
    "title": "Session Termination",
    "family": "Access Control"
  },
  {
    "id": "AC-14",
    "title": "Permitted Actions Without Identification or Authentication",
    "family": "Access Control"
  },
  {
    "id": "AC-17",
    "title": "Remote Access",
    "family": "Access Control"
  },
  {
    "id": "AC-17.1",
    "title": "Monitoring and Control",
    "family": "Access Control"
  },
  {
    "id": "AC-17.2",
    "title": "Protection of Confidentiality and Integrity Using Encryption",
    "family": "Access Control"
  },
  {
    "id": "AC-17.3",
    "title": "Managed Access Control Points",
    "family": "Access Control"
  },
  {
    "id": "AC-17.4",
    "title": "Privileged Commands and Access",
    "family": "Access Control"
  },
  {
    "id": "AC-18",
    "title": "Wireless Access",
    "family": "Access Control"
  },
  {
    "id": "AC-18.1",
    "title": "Authentication and Encryption",
    "family": "Access Control"
  },
  {
    "id": "AC-18.3",
    "title": "Disable Wireless Networking",
    "family": "Access Control"
  },
  {
    "id": "AC-19",
    "title": "Access Control for Mobile Devices",
    "family": "Access Control"
  },
  {
    "id": "AC-19.5",
    "title": "Full Device or Container-based Encryption",
    "family": "Access Control"
  },
  {
    "id": "AC-2",
    "title": "Account Management",
    "family": "Access Control"
  },
  {
    "id": "AC-2.1",
    "title": "Automated System Account Management",
    "family": "Access Control"
  },
  {
    "id": "AC-2.13",
    "title": "Disable Accounts for High-risk Individuals",
    "family": "Access Control"
  },
  {
    "id": "AC-2.2",
    "title": "Automated Temporary and Emergency Account Management",
    "family": "Access Control"
  },
  {
    "id": "AC-2.3",
    "title": "Disable Accounts",
    "family": "Access Control"
  },
  {
    "id": "AC-2.4",
    "title": "Automated Audit Actions",
    "family": "Access Control"
  },
  {
    "id": "AC-2.5",
    "title": "Inactivity Logout",
    "family": "Access Control"
  },
  {
    "id": "AC-20",
    "title": "Use of External Systems",
    "family": "Access Control"
  },
  {
    "id": "AC-20.1",
    "title": "Limits on Authorized Use",
    "family": "Access Control"
  },
  {
    "id": "AC-20.2",
    "title": "Portable Storage Devices — Restricted Use",
    "family": "Access Control"
  },
  {
    "id": "AC-21",
    "title": "Information Sharing",
    "family": "Access Control"
  },
  {
    "id": "AC-22",
    "title": "Publicly Accessible Content",
    "family": "Access Control"
  },
  {
    "id": "AC-3",
    "title": "Access Enforcement",
    "family": "Access Control"
  },
  {
    "id": "AC-4",
    "title": "Information Flow Enforcement",
    "family": "Access Control"
  },
  {
    "id": "AC-5",
    "title": "Separation of Duties",
    "family": "Access Control"
  },
  {
    "id": "AC-6",
    "title": "Least Privilege",
    "family": "Access Control"
  },
  {
    "id": "AC-6.1",
    "title": "Authorize Access to Security Functions",
    "family": "Access Control"
  },
  {
    "id": "AC-6.10",
    "title": "Prohibit Non-privileged Users from Executing Privileged Functions",
    "family": "Access Control"
  },
  {
    "id": "AC-6.2",
    "title": "Non-privileged Access for Nonsecurity Functions",
    "family": "Access Control"
  },
  {
    "id": "AC-6.5",
    "title": "Privileged Accounts",
    "family": "Access Control"
  },
  {
    "id": "AC-6.7",
    "title": "Review of User Privileges",
    "family": "Access Control"
  },
  {
    "id": "AC-6.9",
    "title": "Log Use of Privileged Functions",
    "family": "Access Control"
  },
  {
    "id": "AC-7",
    "title": "Unsuccessful Logon Attempts",
    "family": "Access Control"
  },
  {
    "id": "AC-8",
    "title": "System Use Notification",
    "family": "Access Control"
  },
  {
    "id": "AT-1",
    "title": "Policy and Procedures",
    "family": "Awareness and Training"
  },
  {
    "id": "AT-2",
    "title": "Literacy Training and Awareness",
    "family": "Awareness and Training"
  },
  {
    "id": "AT-2.2",
    "title": "Insider Threat",
    "family": "Awareness and Training"
  },
  {
    "id": "AT-2.3",
    "title": "Social Engineering and Mining",
    "family": "Awareness and Training"
  },
  {
    "id": "AT-3",
    "title": "Role-based Training",
    "family": "Awareness and Training"
  },
  {
    "id": "AT-4",
    "title": "Training Records",
    "family": "Awareness and Training"
  },
  {
    "id": "AU-1",
    "title": "Policy and Procedures",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-11",
    "title": "Audit Record Retention",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-12",
    "title": "Audit Record Generation",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-2",
    "title": "Event Logging",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-3",
    "title": "Content of Audit Records",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-3.1",
    "title": "Additional Audit Information",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-4",
    "title": "Audit Log Storage Capacity",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-5",
    "title": "Response to Audit Logging Process Failures",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-6",
    "title": "Audit Record Review, Analysis, and Reporting",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-6.1",
    "title": "Automated Process Integration",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-6.3",
    "title": "Correlate Audit Record Repositories",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-7",
    "title": "Audit Record Reduction and Report Generation",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-7.1",
    "title": "Automatic Processing",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-8",
    "title": "Time Stamps",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-9",
    "title": "Protection of Audit Information",
    "family": "Audit and Accountability"
  },
  {
    "id": "AU-9.4",
    "title": "Access by Subset of Privileged Users",
    "family": "Audit and Accountability"
  },
  {
    "id": "CA-1",
    "title": "Policy and Procedures",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-2",
    "title": "Control Assessments",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-2.1",
    "title": "Independent Assessors",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-3",
    "title": "Information Exchange",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-5",
    "title": "Plan of Action and Milestones",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-6",
    "title": "Authorization",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-7",
    "title": "Continuous Monitoring",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-7.1",
    "title": "Independent Assessment",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-7.4",
    "title": "Risk Monitoring",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CA-9",
    "title": "Internal System Connections",
    "family": "Assessment, Authorization, and Monitoring"
  },
  {
    "id": "CM-1",
    "title": "Policy and Procedures",
    "family": "Configuration Management"
  },
  {
    "id": "CM-10",
    "title": "Software Usage Restrictions",
    "family": "Configuration Management"
  },
  {
    "id": "CM-11",
    "title": "User-installed Software",
    "family": "Configuration Management"
  },
  {
    "id": "CM-12",
    "title": "Information Location",
    "family": "Configuration Management"
  },
  {
    "id": "CM-12.1",
    "title": "Automated Tools to Support Information Location",
    "family": "Configuration Management"
  },
  {
    "id": "CM-2",
    "title": "Baseline Configuration",
    "family": "Configuration Management"
  },
  {
    "id": "CM-2.2",
    "title": "Automation Support for Accuracy and Currency",
    "family": "Configuration Management"
  },
  {
    "id": "CM-2.3",
    "title": "Retention of Previous Configurations",
    "family": "Configuration Management"
  },
  {
    "id": "CM-2.7",
    "title": "Configure Systems and Components for High-risk Areas",
    "family": "Configuration Management"
  },
  {
    "id": "CM-3",
    "title": "Configuration Change Control",
    "family": "Configuration Management"
  },
  {
    "id": "CM-3.2",
    "title": "Testing, Validation, and Documentation of Changes",
    "family": "Configuration Management"
  },
  {
    "id": "CM-3.4",
    "title": "Security and Privacy Representatives",
    "family": "Configuration Management"
  },
  {
    "id": "CM-4",
    "title": "Impact Analyses",
    "family": "Configuration Management"
  },
  {
    "id": "CM-4.2",
    "title": "Verification of Controls",
    "family": "Configuration Management"
  },
  {
    "id": "CM-5",
    "title": "Access Restrictions for Change",
    "family": "Configuration Management"
  },
  {
    "id": "CM-6",
    "title": "Configuration Settings",
    "family": "Configuration Management"
  },
  {
    "id": "CM-7",
    "title": "Least Functionality",
    "family": "Configuration Management"
  },
  {
    "id": "CM-7.1",
    "title": "Periodic Review",
    "family": "Configuration Management"
  },
  {
    "id": "CM-7.2",
    "title": "Prevent Program Execution",
    "family": "Configuration Management"
  },
  {
    "id": "CM-7.5",
    "title": "Authorized Software — Allow-by-exception",
    "family": "Configuration Management"
  },
  {
    "id": "CM-8",
    "title": "System Component Inventory",
    "family": "Configuration Management"
  },
  {
    "id": "CM-8.1",
    "title": "Updates During Installation and Removal",
    "family": "Configuration Management"
  },
  {
    "id": "CM-8.3",
    "title": "Automated Unauthorized Component Detection",
    "family": "Configuration Management"
  },
  {
    "id": "CM-9",
    "title": "Configuration Management Plan",
    "family": "Configuration Management"
  },
  {
    "id": "CP-1",
    "title": "Policy and Procedures",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-10",
    "title": "System Recovery and Reconstitution",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-10.2",
    "title": "Transaction Recovery",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-2",
    "title": "Contingency Plan",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-2.1",
    "title": "Coordinate with Related Plans",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-2.3",
    "title": "Resume Mission and Business Functions",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-2.8",
    "title": "Identify Critical Assets",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-3",
    "title": "Contingency Training",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-4",
    "title": "Contingency Plan Testing",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-4.1",
    "title": "Coordinate with Related Plans",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-6",
    "title": "Alternate Storage Site",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-6.1",
    "title": "Separation from Primary Site",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-6.3",
    "title": "Accessibility",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-7",
    "title": "Alternate Processing Site",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-7.1",
    "title": "Separation from Primary Site",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-7.2",
    "title": "Accessibility",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-7.3",
    "title": "Priority of Service",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-8",
    "title": "Telecommunications Services",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-8.1",
    "title": "Priority of Service Provisions",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-8.2",
    "title": "Single Points of Failure",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-9",
    "title": "System Backup",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-9.1",
    "title": "Testing for Reliability and Integrity",
    "family": "Contingency Planning"
  },
  {
    "id": "CP-9.8",
    "title": "Cryptographic Protection",
    "family": "Contingency Planning"
  },
  {
    "id": "IA-1",
    "title": "Policy and Procedures",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-11",
    "title": "Re-authentication",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-12",
    "title": "Identity Proofing",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-12.2",
    "title": "Identity Evidence",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-12.3",
    "title": "Identity Evidence Validation and Verification",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-12.5",
    "title": "Address Confirmation",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-2",
    "title": "Identification and Authentication (Organizational Users)",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-2.1",
    "title": "Multi-factor Authentication to Privileged Accounts",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-2.12",
    "title": "Acceptance of PIV Credentials",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-2.2",
    "title": "Multi-factor Authentication to Non-privileged Accounts",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-2.8",
    "title": "Access to Accounts — Replay Resistant",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-3",
    "title": "Device Identification and Authentication",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-4",
    "title": "Identifier Management",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-4.4",
    "title": "Identify User Status",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-5",
    "title": "Authenticator Management",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-5.1",
    "title": "Password-based Authentication",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-5.2",
    "title": "Public Key-based Authentication",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-5.6",
    "title": "Protection of Authenticators",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-6",
    "title": "Authentication Feedback",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-7",
    "title": "Cryptographic Module Authentication",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-8",
    "title": "Identification and Authentication (Non-organizational Users)",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-8.1",
    "title": "Acceptance of PIV Credentials from Other Agencies",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-8.2",
    "title": "Acceptance of External Authenticators",
    "family": "Identification and Authentication"
  },
  {
    "id": "IA-8.4",
    "title": "Use of Defined Profiles",
    "family": "Identification and Authentication"
  },
  {
    "id": "IR-1",
    "title": "Policy and Procedures",
    "family": "Incident Response"
  },
  {
    "id": "IR-2",
    "title": "Incident Response Training",
    "family": "Incident Response"
  },
  {
    "id": "IR-3",
    "title": "Incident Response Testing",
    "family": "Incident Response"
  },
  {
    "id": "IR-3.2",
    "title": "Coordination with Related Plans",
    "family": "Incident Response"
  },
  {
    "id": "IR-4",
    "title": "Incident Handling",
    "family": "Incident Response"
  },
  {
    "id": "IR-4.1",
    "title": "Automated Incident Handling Processes",
    "family": "Incident Response"
  },
  {
    "id": "IR-5",
    "title": "Incident Monitoring",
    "family": "Incident Response"
  },
  {
    "id": "IR-6",
    "title": "Incident Reporting",
    "family": "Incident Response"
  },
  {
    "id": "IR-6.1",
    "title": "Automated Reporting",
    "family": "Incident Response"
  },
  {
    "id": "IR-6.3",
    "title": "Supply Chain Coordination",
    "family": "Incident Response"
  },
  {
    "id": "IR-7",
    "title": "Incident Response Assistance",
    "family": "Incident Response"
  },
  {
    "id": "IR-7.1",
    "title": "Automation Support for Availability of Information and Support",
    "family": "Incident Response"
  },
  {
    "id": "IR-8",
    "title": "Incident Response Plan",
    "family": "Incident Response"
  },
  {
    "id": "MA-1",
    "title": "Policy and Procedures",
    "family": "Maintenance"
  },
  {
    "id": "MA-2",
    "title": "Controlled Maintenance",
    "family": "Maintenance"
  },
  {
    "id": "MA-3",
    "title": "Maintenance Tools",
    "family": "Maintenance"
  },
  {
    "id": "MA-3.1",
    "title": "Inspect Tools",
    "family": "Maintenance"
  },
  {
    "id": "MA-3.2",
    "title": "Inspect Media",
    "family": "Maintenance"
  },
  {
    "id": "MA-3.3",
    "title": "Prevent Unauthorized Removal",
    "family": "Maintenance"
  },
  {
    "id": "MA-4",
    "title": "Nonlocal Maintenance",
    "family": "Maintenance"
  },
  {
    "id": "MA-5",
    "title": "Maintenance Personnel",
    "family": "Maintenance"
  },
  {
    "id": "MA-6",
    "title": "Timely Maintenance",
    "family": "Maintenance"
  },
  {
    "id": "MP-1",
    "title": "Policy and Procedures",
    "family": "Media Protection"
  },
  {
    "id": "MP-2",
    "title": "Media Access",
    "family": "Media Protection"
  },
  {
    "id": "MP-3",
    "title": "Media Marking",
    "family": "Media Protection"
  },
  {
    "id": "MP-4",
    "title": "Media Storage",
    "family": "Media Protection"
  },
  {
    "id": "MP-5",
    "title": "Media Transport",
    "family": "Media Protection"
  },
  {
    "id": "MP-6",
    "title": "Media Sanitization",
    "family": "Media Protection"
  },
  {
    "id": "MP-7",
    "title": "Media Use",
    "family": "Media Protection"
  },
  {
    "id": "PE-1",
    "title": "Policy and Procedures",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-10",
    "title": "Emergency Shutoff",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-11",
    "title": "Emergency Power",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-12",
    "title": "Emergency Lighting",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-13",
    "title": "Fire Protection",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-13.1",
    "title": "Detection Systems — Automatic Activation and Notification",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-14",
    "title": "Environmental Controls",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-15",
    "title": "Water Damage Protection",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-16",
    "title": "Delivery and Removal",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-17",
    "title": "Alternate Work Site",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-2",
    "title": "Physical Access Authorizations",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-3",
    "title": "Physical Access Control",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-4",
    "title": "Access Control for Transmission",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-5",
    "title": "Access Control for Output Devices",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-6",
    "title": "Monitoring Physical Access",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-6.1",
    "title": "Intrusion Alarms and Surveillance Equipment",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-8",
    "title": "Visitor Access Records",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PE-9",
    "title": "Power Equipment and Cabling",
    "family": "Physical and Environmental Protection"
  },
  {
    "id": "PL-1",
    "title": "Policy and Procedures",
    "family": "Planning"
  },
  {
    "id": "PL-10",
    "title": "Baseline Selection",
    "family": "Planning"
  },
  {
    "id": "PL-11",
    "title": "Baseline Tailoring",
    "family": "Planning"
  },
  {
    "id": "PL-2",
    "title": "System Security and Privacy Plans",
    "family": "Planning"
  },
  {
    "id": "PL-4",
    "title": "Rules of Behavior",
    "family": "Planning"
  },
  {
    "id": "PL-4.1",
    "title": "Social Media and External Site/Application Usage Restrictions",
    "family": "Planning"
  },
  {
    "id": "PL-8",
    "title": "Security and Privacy Architectures",
    "family": "Planning"
  },
  {
    "id": "PS-1",
    "title": "Policy and Procedures",
    "family": "Personnel Security"
  },
  {
    "id": "PS-2",
    "title": "Position Risk Designation",
    "family": "Personnel Security"
  },
  {
    "id": "PS-3",
    "title": "Personnel Screening",
    "family": "Personnel Security"
  },
  {
    "id": "PS-4",
    "title": "Personnel Termination",
    "family": "Personnel Security"
  },
  {
    "id": "PS-5",
    "title": "Personnel Transfer",
    "family": "Personnel Security"
  },
  {
    "id": "PS-6",
    "title": "Access Agreements",
    "family": "Personnel Security"
  },
  {
    "id": "PS-7",
    "title": "External Personnel Security",
    "family": "Personnel Security"
  },
  {
    "id": "PS-8",
    "title": "Personnel Sanctions",
    "family": "Personnel Security"
  },
  {
    "id": "PS-9",
    "title": "Position Descriptions",
    "family": "Personnel Security"
  },
  {
    "id": "RA-1",
    "title": "Policy and Procedures",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-2",
    "title": "Security Categorization",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-3",
    "title": "Risk Assessment",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-3.1",
    "title": "Supply Chain Risk Assessment",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-5",
    "title": "Vulnerability Monitoring and Scanning",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-5.11",
    "title": "Public Disclosure Program",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-5.2",
    "title": "Update Vulnerabilities to Be Scanned",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-5.5",
    "title": "Privileged Access",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-7",
    "title": "Risk Response",
    "family": "Risk Assessment"
  },
  {
    "id": "RA-9",
    "title": "Criticality Analysis",
    "family": "Risk Assessment"
  },
  {
    "id": "SA-1",
    "title": "Policy and Procedures",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-10",
    "title": "Developer Configuration Management",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-11",
    "title": "Developer Testing and Evaluation",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-15",
    "title": "Development Process, Standards, and Tools",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-15.3",
    "title": "Criticality Analysis",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-2",
    "title": "Allocation of Resources",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-22",
    "title": "Unsupported System Components",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-3",
    "title": "System Development Life Cycle",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-4",
    "title": "Acquisition Process",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-4.1",
    "title": "Functional Properties of Controls",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-4.10",
    "title": "Use of Approved PIV Products",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-4.2",
    "title": "Design and Implementation Information for Controls",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-4.9",
    "title": "Functions, Ports, Protocols, and Services in Use",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-5",
    "title": "System Documentation",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-8",
    "title": "Security and Privacy Engineering Principles",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-9",
    "title": "External System Services",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SA-9.2",
    "title": "Identification of Functions, Ports, Protocols, and Services",
    "family": "System and Services Acquisition"
  },
  {
    "id": "SC-1",
    "title": "Policy and Procedures",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-10",
    "title": "Network Disconnect",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-12",
    "title": "Cryptographic Key Establishment and Management",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-13",
    "title": "Cryptographic Protection",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-15",
    "title": "Collaborative Computing Devices and Applications",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-17",
    "title": "Public Key Infrastructure Certificates",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-18",
    "title": "Mobile Code",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-2",
    "title": "Separation of System and User Functionality",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-20",
    "title": "Secure Name/Address Resolution Service (Authoritative Source)",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-21",
    "title": "Secure Name/Address Resolution Service (Recursive or Caching Resolver)",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-22",
    "title": "Architecture and Provisioning for Name/Address Resolution Service",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-23",
    "title": "Session Authenticity",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-28",
    "title": "Protection of Information at Rest",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-28.1",
    "title": "Cryptographic Protection",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-39",
    "title": "Process Isolation",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-4",
    "title": "Information in Shared System Resources",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-5",
    "title": "Denial-of-service Protection",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7",
    "title": "Boundary Protection",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7.3",
    "title": "Access Points",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7.4",
    "title": "External Telecommunications Services",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7.5",
    "title": "Deny by Default — Allow by Exception",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7.7",
    "title": "Split Tunneling for Remote Devices",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-7.8",
    "title": "Route Traffic to Authenticated Proxy Servers",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-8",
    "title": "Transmission Confidentiality and Integrity",
    "family": "System and Communications Protection"
  },
  {
    "id": "SC-8.1",
    "title": "Cryptographic Protection",
    "family": "System and Communications Protection"
  },
  {
    "id": "SI-1",
    "title": "Policy and Procedures",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-10",
    "title": "Information Input Validation",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-11",
    "title": "Error Handling",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-12",
    "title": "Information Management and Retention",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-16",
    "title": "Memory Protection",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-2",
    "title": "Flaw Remediation",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-2.2",
    "title": "Automated Flaw Remediation Status",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-3",
    "title": "Malicious Code Protection",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-4",
    "title": "System Monitoring",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-4.2",
    "title": "Automated Tools and Mechanisms for Real-time Analysis",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-4.4",
    "title": "Inbound and Outbound Communications Traffic",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-4.5",
    "title": "System-generated Alerts",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-5",
    "title": "Security Alerts, Advisories, and Directives",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-7",
    "title": "Software, Firmware, and Information Integrity",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-7.1",
    "title": "Integrity Checks",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-7.7",
    "title": "Integration of Detection and Response",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-8",
    "title": "Spam Protection",
    "family": "System and Information Integrity"
  },
  {
    "id": "SI-8.2",
    "title": "Automatic Updates",
    "family": "System and Information Integrity"
  },
  {
    "id": "SR-1",
    "title": "Policy and Procedures",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-10",
    "title": "Inspection of Systems or Components",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-11",
    "title": "Component Authenticity",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-11.1",
    "title": "Anti-counterfeit Training",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-11.2",
    "title": "Configuration Control for Component Service and Repair",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-12",
    "title": "Component Disposal",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-2",
    "title": "Supply Chain Risk Management Plan",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-2.1",
    "title": "Establish SCRM Team",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-3",
    "title": "Supply Chain Controls and Processes",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-5",
    "title": "Acquisition Strategies, Tools, and Methods",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-6",
    "title": "Supplier Assessments and Reviews",
    "family": "Supply Chain Risk Management"
  },
  {
    "id": "SR-8",
    "title": "Notification Agreements",
    "family": "Supply Chain Risk Management"
  }
]
